KNN, SVM, Randomforest, Logistic Regression, Decision tree

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving creditcard.csv to creditcard.csv


In [ ]:
dataset = pd.read_csv('creditcard.csv')
dataset

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [ ]:
dataset.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
dataset.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.654067e-16 -3.568593e-16  2.578648e-16  4.473266e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   5.340915e-16  1.683437e-15 -3.660091e-16 -1.227390e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [ ]:
#Count total number of classes in Data
class_counts = dataset.groupby('Class').size()
print(class_counts)

Class
0    284315
1       492
dtype: int64


In [ ]:
# separating the data for analysis
legit = dataset[dataset.Class==0]
fraud = dataset[dataset.Class==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)


In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

In [ ]:
# compare the values for both transactions
dataset.groupby('Class').mean()

In [ ]:
legit_sample = legit.sample(n=492)

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset

In [ ]:
new_dataset.describe()

Time          V1          V2          V3          V4  \
count     984.000000  984.000000  984.000000  984.000000  984.000000   
mean    87268.201220   -2.273214    1.776462   -3.535973    2.258878   
std     46851.642906    5.540451    3.684485    6.207622    3.202668   
min       222.000000  -30.552380   -8.402154  -31.103685   -4.729482   
25%     48333.000000   -2.744364   -0.223072   -5.084967   -0.027611   
50%     78360.000000   -0.665264    0.786369   -1.405652    1.287041   
75%    132692.500000    1.118388    2.814266    0.323357    4.235631   
max    171122.000000    2.361583   22.057729    3.212677   12.114672   

               V5          V6          V7          V8          V9  ...  \
count  984.000000  984.000000  984.000000  984.000000  984.000000  ...   
mean    -1.614246   -0.652376   -2.783846    0.311880   -1.235195  ...   
std      4.187450    1.787026    5.845531    4.853655    2.357200  ...   
min    -22.105532   -6.406267  -43.557242  -41.044261  -13.434066  ...   
25%     -1.835182   -1.572363   -3.044451   -0.205668   -2.297633  ...   
50%     -0.499829   -0.649913   -0.644578    0.162398   -0.678169  ...   
75%      0.412375    0.111023    0.254476    0.867939    0.233594  ...   
max     11.095089    6.474115    5.802537   20.007208    5.718008  ...   

              V21         V22         V23         V24         V25         V26  \
count  984.000000  984.000000  984.000000  984.000000  984.000000  984.000000   
mean     0.358873    0.010087   -0.029840   -0.058852    0.017956    0.019333   
std      2.779631    1.170456    1.216055    0.575578    0.677676    0.491657   
min    -22.797604   -8.887017  -19.254328   -2.028024   -4.781606   -1.234159   
25%     -0.166343   -0.523430   -0.240046   -0.410897   -0.314741   -0.305311   
50%      0.146469    0.033940   -0.034907   -0.004826    0.052299   -0.020753   
75%      0.652748    0.583915    0.199651    0.374149    0.392689    0.338893   
max     27.202839    8.361985    6.622215    1.250645    2.208209    2.745261   

              V27         V28       Amount       Class  
count  984.000000  984.000000   984.000000  984.000000  
mean     0.087965    0.030433   112.791118    0.500000  
std      1.003234    0.430102   262.323570    0.500254  
min     -7.263482   -2.910813     0.000000    0.000000  
25%     -0.064750   -0.056559     1.520000    0.000000  
50%      0.047129    0.030233    20.000000    0.500000  
75%      0.424868    0.209271    99.990000    1.000000  
max      3.052358    1.779364  2602.700000    1.000000  

[8 rows x 31 columns]

In [ ]:
X  = new_dataset.iloc[:,1:30]
y = new_dataset.iloc[:, 30:31]

In [ ]:
print(X)

In [ ]:
print(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

In [ ]:
print(X_train)

In [ ]:
print(X_test)

In [ ]:
print(y_train)

        Class
42007       1
149355      0
144752      0
57040       0
143744      0
...       ...
10568       1
27749       1
623         1
9252        1
225919      0

[787 rows x 1 columns]


In [ ]:
print(y_test)

        Class
188237      0
11343       1
150715      1
223928      0
58761       1
...       ...
251881      1
209002      0
15539       1
50211       1
88298       0

[197 rows x 1 columns]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform (X_test)
print(np.mean(X_train))
print(np.std(X_train))

-7.938851054586405e-18
1.0


# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train.values.ravel())
y_pred0 = log_reg.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred0)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[90  5]
 [ 9 93]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.3f' % (accuracy_score(y_test, y_pred0)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision = precision_score(y_test, y_pred0, average='binary')
print('Precision: %.3f' % (precision*100))
recall = recall_score(y_test, y_pred0, average='binary')
print('Recall: %.3f' % (recall*100))
score = f1_score(y_test, y_pred0, average='binary')
print('F-Measure: %.3f' % (score*100))

Accuracy: 92.893
Precision: 94.898
Recall: 91.176
F-Measure: 93.000


In [ ]:
score = log_reg.score(X_test, y_test)
print(score)

0.9289340101522843


In [ ]:
V1 = -2.3122265423263 #@param {type:"number"}

V2 = 1.95199201064158 #@param {type:"number"}

V3 = -1.60985073229769 #@param {type:"number"}

V4 = 3.9979055875468 #@param {type:"number"}

V5 = -0.522187864667764 #@param {type:"number"}

V6 = -1.42654531920595 #@param {type:"number"}

V7 = -2.53738730624579 #@param {type:"number"}

V8 = 1.39165724829804 #@param {type:"number"}

V9 = -2.77008927719433 #@param {type:"number"}

V10 = -2.77227214465915 #@param {type:"number"}

V11 = 3.20203320709635 #@param {type:"number"}

V12 = -2.89990738849473 #@param {type:"number"}

V13 = -0.595221881324605 #@param {type:"number"}

V14 = -4.28925378244217 #@param {type:"number"}

V15 = 0.389724120274487 #@param {type:"number"}

V16 = -1.14074717980657 #@param {type:"number"}

V17 = -2.83005567450437 #@param {type:"number"}

V18 = -0.0168224681808257 #@param {type:"number"}

V19 = 0.416955705037907 #@param {type:"number"}

V20 = 0.126910559061474 #@param {type:"number"}

V21 = 0.517232370861764 #@param {type:"number"}

V22 = -0.0350493686052974 #@param {type:"number"}

V23 = -0.465211076182388 #@param {type:"number"}

V24 = 0.320198198514526 #@param {type:"number"}

V25 = 0.0445191674731724 #@param {type:"number"}

V26 = 0.177839798284401 #@param {type:"number"}

V27 = 0.261145002567677 #@param {type:"number"}

V28 = -0.143275874698919 #@param {type:"number"}

Amount = 0 #@param {type:"number"}

output=log_reg.predict(sc.transform([[V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount]]))

print("Class =", output)

if output==[1]:
  print('It is a Fraud')
else:
  print('It is not Fraud')

Class = [1]
It is a Fraud


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pickle 
print("[INFO] Saving model...")
saved_model0=pickle.dump(log_reg,open('/content/drive/My Drive/Colab Notebooks/Logistic_Major.pkl', 'wb'))

[INFO] Saving model...


In [ ]:
model0 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Logistic_Major.pkl','rb'))
model0.predict(X_test)

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

# KNN Algorithm


In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier =  KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=15)

In [ ]:
y_pred1 = classifier.predict(X_test)
y_pred1

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred1)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[93  2]
 [11 91]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred1)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision = precision_score(y_test, y_pred1, average='binary')
print('Precision: %.2f' % (precision*100))
recall = recall_score(y_test, y_pred1, average='binary')
print('Recall: %.3f' % (recall*100))
score = f1_score(y_test, y_pred1, average='binary')
print('F-Measure: %.3f' % (score*100))

Accuracy: 93.40
Precision: 97.85
Recall: 89.216
F-Measure: 93.333


In [ ]:
V1 = -2.3122265423263 #@param {type:"number"}

V2 = 1.95199201064158 #@param {type:"number"}

V3 = -1.60985073229769 #@param {type:"number"}

V4 = 3.9979055875468 #@param {type:"number"}

V5 = -0.522187864667764 #@param {type:"number"}

V6 = -1.42654531920595 #@param {type:"number"}

V7 = -2.53738730624579 #@param {type:"number"}

V8 = 1.39165724829804 #@param {type:"number"}

V9 = -2.77008927719433 #@param {type:"number"}

V10 = -2.77227214465915 #@param {type:"number"}

V11 = 3.20203320709635 #@param {type:"number"}

V12 = -2.89990738849473 #@param {type:"number"}

V13 = -0.595221881324605 #@param {type:"number"}

V14 = -4.28925378244217 #@param {type:"number"}

V15 = 0.389724120274487 #@param {type:"number"}

V16 = -1.14074717980657 #@param {type:"number"}

V17 = -2.83005567450437 #@param {type:"number"}

V18 = -0.0168224681808257 #@param {type:"number"}

V19 = 0.416955705037907 #@param {type:"number"}

V20 = 0.126910559061474 #@param {type:"number"}

V21 = 0.517232370861764 #@param {type:"number"}

V22 = -0.0350493686052974 #@param {type:"number"}

V23 = -0.465211076182388 #@param {type:"number"}

V24 = 0.320198198514526 #@param {type:"number"}

V25 = 0.0445191674731724 #@param {type:"number"}

V26 = 0.177839798284401 #@param {type:"number"}

V27 = 0.261145002567677 #@param {type:"number"}

V28 = -0.143275874698919 #@param {type:"number"}

Amount = 0 #@param {type:"number"}

output1=classifier.predict(sc.transform([[V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount]]))

print("Class =", output1)

if output1==[1]:
  print( 'It is a Fraud')
else:
  print('It is not Fraud')

Class = [1]
It is a Fraud


In [ ]:
import pickle 
print("[INFO] Saving model...")
saved_model1=pickle.dump(classifier,open('/content/drive/My Drive/Colab Notebooks/KNN_Major.pkl', 'wb'))

[INFO] Saving model...


In [ ]:
model1 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/KNN_Major.pkl','rb'))
model1.predict(X_test)

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

# Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 5)
classifier1.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=5)

In [ ]:
y_pred2 = classifier1.predict(X_test)
y_pred2

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred2)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[79 16]
 [ 8 94]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred2)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision = precision_score(y_test, y_pred2, average='binary')
print('Precision: %.2f' % (precision*100))
recall = recall_score(y_test, y_pred2, average='binary')
print('Recall: %.3f' % (recall*100))
score = f1_score(y_test, y_pred2, average='binary')
print('F-Measure: %.3f' % (score*100))

Accuracy: 87.82
Precision: 85.45
Recall: 92.157
F-Measure: 88.679


In [ ]:
V1 = -2.3122265423263 #@param {type:"number"}

V2 = 1.95199201064158 #@param {type:"number"}

V3 = -1.60985073229769 #@param {type:"number"}

V4 = 3.9979055875468 #@param {type:"number"}

V5 = -0.522187864667764 #@param {type:"number"}

V6 = -1.42654531920595 #@param {type:"number"}

V7 = -2.53738730624579 #@param {type:"number"}

V8 = 1.39165724829804 #@param {type:"number"}

V9 = -2.77008927719433 #@param {type:"number"}

V10 = -2.77227214465915 #@param {type:"number"}

V11 = 3.20203320709635 #@param {type:"number"}

V12 = -2.89990738849473 #@param {type:"number"}

V13 = -0.595221881324605 #@param {type:"number"}

V14 = -4.28925378244217 #@param {type:"number"}

V15 = 0.389724120274487 #@param {type:"number"}

V16 = -1.14074717980657 #@param {type:"number"}

V17 = -2.83005567450437 #@param {type:"number"}

V18 = -0.0168224681808257 #@param {type:"number"}

V19 = 0.416955705037907 #@param {type:"number"}

V20 = 0.126910559061474 #@param {type:"number"}

V21 = 0.517232370861764 #@param {type:"number"}

V22 = -0.0350493686052974 #@param {type:"number"}

V23 = -0.465211076182388 #@param {type:"number"}

V24 = 0.320198198514526 #@param {type:"number"}

V25 = 0.0445191674731724 #@param {type:"number"}

V26 = 0.177839798284401 #@param {type:"number"}

V27 = 0.261145002567677 #@param {type:"number"}

V28 = -0.143275874698919 #@param {type:"number"}

Amount = 0 #@param {type:"number"}

output2 = classifier1.predict(sc.transform([[V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount]]))

print("Class =", output2)

if output2==[1]:
  print( 'It is a Fraud')
else:
  print('It is not Fraud')



Class = [1]
It is a Fraud


In [ ]:
import pickle 
print("[INFO] Saving model...")
saved_model2=pickle.dump(classifier1,open('/content/drive/My Drive/Colab Notebooks/Decision-Tree_Major.pkl', 'wb'))

[INFO] Saving model...


In [ ]:
model2 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Decision-Tree_Major.pkl','rb'))
model2.predict(X_test)

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

# Random Forest Alogorithm

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_Random = RandomForestClassifier(n_estimators = 300, criterion = 'entropy', random_state = 5)
classifier_Random.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(criterion='entropy', n_estimators=300, random_state=5)

In [ ]:
y_pred3 = classifier_Random.predict(X_test)
y_pred3

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred3)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[91  4]
 [ 8 94]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred3)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision = precision_score(y_test, y_pred3, average='binary')
print('Precision: %.2f' % (precision*100))
recall = recall_score(y_test, y_pred3, average='binary')
print('Recall: %.3f' % (recall*100))
score = f1_score(y_test, y_pred3, average='binary')
print('F-Measure: %.3f' % (score*100))

Accuracy: 93.91
Precision: 95.92
Recall: 92.157
F-Measure: 94.000


In [ ]:
V1 = -2.3122265423263 #@param {type:"number"}

V2 = 1.95199201064158 #@param {type:"number"}

V3 = -1.60985073229769 #@param {type:"number"}

V4 = 3.9979055875468 #@param {type:"number"}

V5 = -0.522187864667764 #@param {type:"number"}

V6 = -1.42654531920595 #@param {type:"number"}

V7 = -2.53738730624579 #@param {type:"number"}

V8 = 1.39165724829804 #@param {type:"number"}

V9 = -2.77008927719433 #@param {type:"number"}

V10 = -2.77227214465915 #@param {type:"number"}

V11 = 3.20203320709635 #@param {type:"number"}

V12 = -2.89990738849473 #@param {type:"number"}

V13 = -0.595221881324605 #@param {type:"number"}

V14 = -4.28925378244217 #@param {type:"number"}

V15 = 0.389724120274487 #@param {type:"number"}

V16 = -1.14074717980657 #@param {type:"number"}

V17 = -2.83005567450437 #@param {type:"number"}

V18 = -0.0168224681808257 #@param {type:"number"}

V19 = 0.416955705037907 #@param {type:"number"}

V20 = 0.126910559061474 #@param {type:"number"}

V21 = 0.517232370861764 #@param {type:"number"}

V22 = -0.0350493686052974 #@param {type:"number"}

V23 = -0.465211076182388 #@param {type:"number"}

V24 = 0.320198198514526 #@param {type:"number"}

V25 = 0.0445191674731724 #@param {type:"number"}

V26 = 0.177839798284401 #@param {type:"number"}

V27 = 0.261145002567677 #@param {type:"number"}

V28 = -0.143275874698919 #@param {type:"number"}

Amount = 0 #@param {type:"number"}

output3 = classifier_Random.predict(sc.transform([[V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount]]))

print("Class =", output3)

if output3==[1]:
  print( 'It is a Fraud')
else:
  print('It is not Fraud')



Class = [1]
It is a Fraud


In [ ]:
import pickle 
print("[INFO] Saving model...")
saved_model3=pickle.dump(classifier_Random,open('/content/drive/My Drive/Colab Notebooks/Random-Forest_Major.pkl', 'wb'))

[INFO] Saving model...


In [ ]:
model3 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Random-Forest_Major.pkl','rb'))
model3.predict(X_test)

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

# SVM Algorithm

In [ ]:
from sklearn.svm import SVC
classifier2 = SVC(kernel = 'rbf', random_state = 5, probability=True)
classifier2.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(probability=True, random_state=5)

In [ ]:
y_pred4 = classifier2.predict(X_test)
y_pred4

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred4)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[93  2]
 [10 92]]


In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred4)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision = precision_score(y_test, y_pred4, average='binary')
print('Precision: %.2f' % (precision*100))
recall = recall_score(y_test, y_pred4, average='binary')
print('Recall: %.3f' % (recall*100))
score = f1_score(y_test, y_pred4, average='binary')
print('F-Measure: %.3f' % (score*100))

Accuracy: 93.91
Precision: 97.87
Recall: 90.196
F-Measure: 93.878


In [ ]:
V1 = -2.3122265423263 #@param {type:"number"}

V2 = 1.95199201064158 #@param {type:"number"}

V3 = -1.60985073229769 #@param {type:"number"}

V4 = 3.9979055875468 #@param {type:"number"}

V5 = -0.522187864667764 #@param {type:"number"}

V6 = -1.42654531920595 #@param {type:"number"}

V7 = -2.53738730624579 #@param {type:"number"}

V8 = 1.39165724829804 #@param {type:"number"}

V9 = -2.77008927719433 #@param {type:"number"}

V10 = -2.77227214465915 #@param {type:"number"}

V11 = 3.20203320709635 #@param {type:"number"}

V12 = -2.89990738849473 #@param {type:"number"}

V13 = -0.595221881324605 #@param {type:"number"}

V14 = -4.28925378244217 #@param {type:"number"}

V15 = 0.389724120274487 #@param {type:"number"}

V16 = -1.14074717980657 #@param {type:"number"}

V17 = -2.83005567450437 #@param {type:"number"}

V18 = -0.0168224681808257 #@param {type:"number"}

V19 = 0.416955705037907 #@param {type:"number"}

V20 = 0.126910559061474 #@param {type:"number"}

V21 = 0.517232370861764 #@param {type:"number"}

V22 = -0.0350493686052974 #@param {type:"number"}

V23 = -0.465211076182388 #@param {type:"number"}

V24 = 0.320198198514526 #@param {type:"number"}

V25 = 0.0445191674731724 #@param {type:"number"}

V26 = 0.177839798284401 #@param {type:"number"}

V27 = 0.261145002567677 #@param {type:"number"}

V28 = -0.143275874698919 #@param {type:"number"}

Amount = 0 #@param {type:"number"}

output4 = classifier2.predict(sc.transform([[V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount]]))

print("Class =", output4)

if output4==[1]:
  print( 'It is a Fraud')
else:
  print('It is not Fraud')



Class = [1]
It is a Fraud


In [ ]:
import pickle 
print("[INFO] Saving model...")
saved_model4=pickle.dump(classifier2,open('/content/drive/My Drive/Colab Notebooks/SVM_Major.pkl', 'wb'))

[INFO] Saving model...


In [ ]:
model4 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/SVM_Major.pkl','rb'))
model4.predict(X_test)

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [ ]:
!pip install flask-ngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# HTML Pages

In [ ]:
%mkdir templates -p

In [ ]:
%mkdir static -p

In [ ]:
%mkdir static/css -p 
%mkdir static/image -p

In [ ]:
%%writefile templates/index.html
<!DOCTYPE html>
<html >
<!--From https://codepen.io/frytyler/pen/EGdtg-->
<head>
<title>Credit Card Fraud Detection</title>
<meta charset="UTF-8">
<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> 
<nav style="width: 100%;" class="myReference">
<a class="  navbar-brand" href="#" style="margin-left: 0px; margin-top: 0px; margin-right: 0px; margin-botttom: 0px;">
    <img style="max-height: auto; width:100%;" src="{{ url_for('static',filename = 'image/PIET logo with tagline.jpg')  }}" 
    class="img-responsive" style="margin-top:0px;style=width: auto; height: auto; min-width:100%; min-height: auto;">
 <ul class='nav-links'>
 <li><a class="active" href="/aboutme">About</a></li>
</ul>
<style><!DOCTYPE html>

h1 {text-align: center;}
h2 {text-align: center;}
h3 {text-align: center;}
p {text-align: center;}
div {text-align: center;}
</style>

<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}
.myDiv {
  border: 10px outset lightblue;
  background-color: lightblue;    
  text-align: center;
}

.button {
  background-color: lightblue;
  border: none;
  color: white;
  padding: 16px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  transition-duration: 0.4s;
  cursor: pointer;

}
.button1 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button1:hover {
  background-color: #f64949ab;
  color: white;
}

.button2 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button2:hover {
  background-color: #37bea5;
  color: white;
}

.button3 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button3:hover {
  background-color: #9c0e9d;
  color: white;
}

.button4 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button4:hover {
  background-color: #b1c711;
  color: white;
}

.button5 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button5:hover {
  background-color: #740821;
  color: white;
}

.button6 {
  background-color: white; 
  color: black; 
  border: 5px solid darkblue;
}

.button6:hover {
  background-color: #0eab60;
  color: white;
}
</style>
</head>

<body>
      
<div class="myDiv" style="background-color:grey;" >
           
<div class="col-md-12">
<center><p style="font-size:40px;color:white;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
<center><p style="font-size:30px;color:white;margin-top:10px;">Department of Computer Engineering</p></center> 
<center><p style="font-size:25px;color:white;margin-top:10px;">Summer Internship 2022 on Machine learning and Data Science</p></center> 
</div>

<div class="login">
<h2 ><u>Analysis to Predict whether it is a fraud or not</u></h2>
<h3><i><u>Developed by Alok Raj</i></u></h3>
<!-- Main Input For Receiving Query to our ML -->
<form action="{{ url_for('predict')}}"method="get">


<div class="form-floating mb-3">

<input type="number" class="form-control" id="V1" name="V1" step="any" min="-31.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V1</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V2" name="V2" step="any" min="-15.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V2</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V3" name="V3" step="any" min="-32.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V3</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V4" name="V4" step="any" min="-4.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V4</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V5" name="V5" step="any" min="-23.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V5</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V6" name="V6" step="any" min="-7.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V6</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V7" name="V7" step="any" min="-44.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V7</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V8" name="V8" step="any" min="-42.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V8</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V9" name="V9" step="any" min="-14.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V9</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V10" name="V10" step="any" min="-25.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V10</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V11" name="V11" step="any" min="-3.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V11</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V12" name="V12" step="any" min="-19.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V12</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V13" name="V13" step="any" min="-4.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V13</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V14" name="V14" step="any" min="-20.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V14</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V15" name="V15" step="any" min="-5.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V15</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V16" name="V16" step="any" min="-15.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V16</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V17" name="V17" step="any" min="-26.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V17</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V18" name="V18" step="any" min="-10.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V18</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V19" name="V19" step="any" min="-4.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V19</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V20" name="V20" step="any" min="-5.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V20</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V21" name="V21" step="any" min="-23.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V21</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V22" name="V22" step="any" min="-9.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V22</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V23" name="V23" step="any" min="-20.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V23</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V24" name="V24" step="any" min="-3.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V24</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V25" name="V25" step="any" min="-5.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V25</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V26" name="V26" step="any" min="-2.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V26</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V27" name="V27" step="any" min="-8.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V27</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="V28" name="V28" step="any" min="-2.0" max="100.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of V28</label>
</div>
<br>

<div class="form-floating mb-3">

<input type="number" class="form-control" id="Amount" name="Amount" step="any" min="0.0" max="5000.0" placeholder="0" required="required">
<label for="floatingInput">Enter value of Amount</label>
</div>
<br>

<br>
 <div class="col-md-4" style="color: #FFF;">
                <label for="inputState" class="form-label">Choose a Model</label>
                <select id="Model" name ="Model" step = "any" class="form-select" required>
                    <option selected>Logistic Prediction</option>
                    <option>KNN Prediction</option>
                    <option>Decision Tree Prediction</option>
                    <option>Random Forest Prediction</option>
                    <option>SVM Prediction</option>
                </select>
            </div>
            <br>
            <div class="col-12">
                <button type="submit" value="NB" name="NB" class="btn btn-outline-danger">Submit</button>
            </div>
</form>
<br>
<br>

<div class="myDiv">
<h2>
{{ prediction_text }}
</h2>
</div>

</div>

<div class="" style="background-color:green;" >
<div class="clearfix">
           
<div class="col-md-12">
 <center><p style="font-size:25px;color:white;margin-top:20px;border: 10px outset #37b486;">Experiment Performed in Summer internship 2022 from 27 June to 8 August </p></center> 
</div>
</div>
</div>
    <br>
    
    <div class="col-md-12">
              <center><h3 class="section-title" style="text-align: center;">Sponsored by</h3></center>
            </div>
          
          <br>
          <br>
    
      <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-4">
                <div class="card mb-3">
            
                    <div class="card">
                        <img style="max-height: 200px;" src="{{ url_for('static',filename = 'image/AICTEIdeaLabFooterLogo.png')  }}"
                            class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title" style="text-align:center">IDEA LAB</h5>
                            
                        </div>
            
            
                    </div>
                </div>
            </div>
            
            <div class="col-xs-12 col-md-4">
                <div class="card mb-3">
            
                    <div class="card">
                        <img style="max-height: 200px;" src="{{ url_for('static',filename = 'image/nbanew.png')  }}"
                            class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title" style="text-align:center">NBA</h5>
                            
                        </div>
            
            
                    </div>
                </div>
            </div>
            
            <div class="col-xs-10 col-md-3">
                <div class="card mb-3">

                    <div class="card">
                        <img style="max-height: 200px;"
                            src="{{ url_for('static',filename = 'image/aicte-logo.png')  }}"
                            class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title"; style="text-align:center">AICTE MODROB DEEP LEARNING LAB</h5>
                            
                        </div>

                    </div>

                </div>
            </div>
        
               
    
    <br><br><br><br><br>
    <div class="fixed-bottom ">
        <div class="bg-secondary " style="min-height: 40px;">

            <marquee style="color:#fff; margin-top: 7px;">
                <h9>Developed by Department of Computer Engineering, PIET</h9>
            </marquee>
        </div>
    </div>
    <!-- change later-->
    <script src="{{ url_for('static',filename = 'js/bootstrap.bundle.min.js')  }}"></script>
</body>
</html>

Overwriting templates/index.html


In [ ]:
%%writefile templates/aboutme.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link href="{{ url_for('static',filename = 'css/bootstrap.min.css')  }}" rel="stylesheet">

    <title>About</title>
    <style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover {
  background-color: #111;
}
.myDiv {
  border: 10px outset #577ac0b5;
  background-color: #917a3778;    
  text-align: center;
  color: white;
}

.my_Div {
  border: 10px outset #7bf797;
  background-color: #da4f8e;    
  text-align: center;
}


.myReference {
  border: 10px outset #f7f37bc2;
  background-color: #210b0bc7;    
  text-align: center;
}

.button {
  background-color: lightblue;
  border: none;
  color: white;
  padding: 16px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  transition-duration: 0.4s;
  cursor: pointer;

}
.button1 {
  background-color: white; 
  color: black; 
  border: 5px solid #7e50c4db;
}

.button1:hover {
  background-color: #f64949ab;
  color: aqua;
}

.button2 {
  background-color: white; 
  color: black; 
  border: 5px solid #bd4d73c9;
}

.button2:hover {
  background-color: #0eab60;
  color: aqua;
}
.blink {
            animation: blinker 1.5s linear infinite;
            color: burlywood;
            font-family: sans-serif;
        }
        @keyframes blinker {
            50% {
                opacity: 0;
            }
        }
        
.blink1 {
            animation: blinker 1.5s linear infinite;
            color: azure;
            font-family: sans-serif;
        }
        @keyframes blinker {
            50% {
                opacity: 0;
            }
        }
        
.animate-charcter
{
   text-transform: uppercase;
  background-image: linear-gradient(
    -225deg,
    #231557 0%,
    #44107a 29%,
    #ff1361 67%,
    #fff800 100%
  );
  background-size: auto auto;
  background-clip: border-box;
  background-size: 200% auto;
  color: #fff;
  background-clip: text;
  text-fill-color: transparent;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  animation: textclip 2s linear infinite;
  display: inline-block;
      font-size: 50px;
}

@keyframes textclip {
  to {
    background-position: 200% center;
  }
}

</style>
</head>

<body>
    <nav style="width: 100%;" class="myReference">
        <a class="  navbar-brand" href="#" style="margin-left: 0px; margin-top: 0px; margin-right: 0px; margin-botttom: 0px;">
             <img style="max-height: auto; width:100%;" src="{{ url_for('static',filename = 'image/PIET logo with tagline.jpg')  }}" 
             class="img-responsive" style="margin-top:0px;style=width: auto; height: auto; min-width:100%; min-height: auto;">
          
          
          
              
              <ul class='nav-links'>
 <li><a class="active" href="/">Home</a></li>
</ul>
            
      </div>
           
        </a>
        
    </nav>

    <div class="myReference">
        <div class="row">
            <div class="col-5 d-none d-sm-block d-sm-none d-md-block d-md-none d-lg-block">

                <img src="{{ url_for('static',filename = 'image/Auriga.jpeg')  }}" class="img-fluid"
                    style="width: auto; height: auto; min-width: 500px;min-height: 600px;">

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-7 " style=" padding: 30px;">
                <h1 class="animate-charcter">About Poornima</h1>
                <br>
                <p style="font-size:20px;text-align:justify; color:blue">The Department of Computer Engineering was incepted in the year 2007 with the vision, “To create an environment in which new ideas, research and technology development and the technocrats and innovators of tomorrow become competent to face the global challenges”, In these academic years Department of Computer Engineering (CS), PIET has achieved lot of success and earn many achievements. I am glad to inform that Department has been accredited by National Board of Accreditation (NBA) in year 2017-18 and it is now in elite list of departments in India. It has taken initiative to start own portal for the home assignment submission and awarding marks. There is many other software are also used which are developed by the faculty members and students of Department such as cspiet.poornima.org, KYS, cstech.poornima.org. Because of all this efforts and team work Department has been recognized as one of the most innovative department in Poornima foundation. </p>
              
                
                <br><br>
                
            </div>
        </div>
    </div>
<h1 style="text-align:center">Contribution</h1>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-4">
                
            </div>
            
         <div class="col-xs-12 col-md-4">
                <div class="card mb-4">
            
                    <div class="myReference">
                        <img style="max-height: 500px;" src="{{ url_for('static',filename = 'image/AlokSnapFinal.jpg')  }}"
                            class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text"; style="text-align:justify">Alok Raj, Student, Department of Computer Engineering, PIET</p>
            
                            
                        </div>
            
            
                    </div>
                </div>
            </div>
                 
    <br><br><br><br><br><br>
    
     <h1 class="animate-charcter">About Me</h1>
      <br><br>
     <P style="font-size:20px;text-align:justify">Alok Raj a 3rd year student at Poornima Institute of Engineering and Technology in Computer Science Branch.I have technical skills like C, C++, Python, Machine Learning.<br>
     </P>     
   <br>
   <br>
   
               
                
                
     <br>
     <br>
     <br><br><br><br><br><br>
    
    <div class="myDiv">
        <marquee class="blink1" width="80%" direction="left" scrollamount="12" height="100px">
        <h1>
            This model is developed by Alok Raj(Student of Computer Science Engineering Department) under the guidance of Deepak Moud, HOD of Computer Science Department, PIET 
            </h1>
        </p>
        </marquee>
    </div>
    <!-- change later-->
    <script src="{{ url_for('static',filename = 'js/bootstrap.bundle.min.js')  }}"></script>

</body>

</html>

Overwriting templates/aboutme.html


In [ ]:
#%%writefile templates/Minor.html



UsageError: %%writefile is a cell magic, but the cell body is empty.


In [ ]:
!pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!ngrok authtoken 2CT4MHWPe5W1c3i8WbPIkMfV3YB_7M1jKwhLC4HVFvS11Rbf

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [ ]:
import numpy as np
from flask import Flask, request, jsonify, render_template
from flask_ngrok import run_with_ngrok
import pickle


app = Flask(__name__)
model0 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Logistic_Major.pkl','rb'))
model1 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/KNN_Major.pkl','rb'))
model2 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Decision-Tree_Major.pkl','rb'))
model3 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/Random-Forest_Major.pkl','rb'))
model4 = pickle.load(open('/content/drive/My Drive/Colab Notebooks/SVM_Major.pkl','rb'))
run_with_ngrok(app)

@app.route('/')
def home():
  
    return render_template("index.html")

@app.route('/aboutme')
def aboutusnew():
    return render_template('aboutme.html')
  
@app.route('/predict',methods=['GET'])

def predict():
    
    V1 = float(request.args.get('V1'))
    V2 = float(request.args.get('V2'))
    V3 = float(request.args.get('V3'))
    V4 = float(request.args.get('V4'))
    V5 = float(request.args.get('V5'))
    V6 = float(request.args.get('V6'))
    V7 = float(request.args.get('V7'))
    V8 = float(request.args.get('V8'))
    V9 = float(request.args.get('V9'))
    V10 = float(request.args.get('V10'))
    V11 = float(request.args.get('V11'))
    V12 = float(request.args.get('V12'))
    V13 = float(request.args.get('V13'))
    V14 = float(request.args.get('V14'))
    V15 = float(request.args.get('V15'))
    V16 = float(request.args.get('V16'))
    V17 = float(request.args.get('V17'))
    V18 = float(request.args.get('V18'))
    V19 = float(request.args.get('V19'))
    V20 = float(request.args.get('V20'))
    V21 = float(request.args.get('V21'))
    V22 = float(request.args.get('V22'))
    V23 = float(request.args.get('V23'))
    V24 = float(request.args.get('V24'))
    V25 = float(request.args.get('V25'))
    V26 = float(request.args.get('V26'))
    V27 = float(request.args.get('V27'))
    V28 = float(request.args.get('V28'))
    Amount = float(request.args.get('Amount'))

# CreditScore	Geography	Gender	Age	Tenure	Balance	NumOfProducts	HasCrCard	IsActiveMember	EstimatedSalary
    Model = str(request.args.get('Model'))

    if Model=='Logistic Prediction':
      prediction = model0.predict([[V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount]])
    
    elif Model=='KNN Prediction':
      prediction = model1.predict([[V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount]])
    
    elif Model=='Decision Tree Prediction':
      prediction = model2.predict([[V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount]])

    elif Model=='Random Forest Prediction':
      prediction = model3.predict([[V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount]])

    else:
      prediction = model4.predict([[V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount]])

    
    if prediction == [1]:
      text = "It is a Fraud"
    else:
      text = "It is not Fraud"

    return render_template('index.html', prediction_text= 'Prediction says: {}'.format(text))

app.run()


 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://1096-34-148-207-118.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


INFO:werkzeug:127.0.0.1 - - [18/Aug/2022 18:18:26] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2022 18:18:26] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2022 18:18:26] "GET /static/image/PIET%20logo%20with%20tagline.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2022 18:18:26] "GET /static/image/nbanew.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2022 18:18:26] "GET /static/image/aicte-logo.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2022 18:18:26] "GET /static/image/AICTEIdeaLabFooterLogo.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2022 18:18:29] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2022 18:18:39] "GET /aboutme HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2022 18:18:39] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Aug/2022 18:18:39] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 404 -
INFO:werkzeug: